version: '3'

services:
  
  backend:
    image: 'backend'
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - '4000:4000'
  
  frontend:
    image: 'frontend'
    networks:
      - frontend
      
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend
    
  